prod fix

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -72,5 +72,5 @@ jobs:
         run: |
           echo "Waiting for services to start..."
           sleep 30  # Give services time to start
-          curl -I http://147.93.105.228:5173 || { echo "Validation failed: Service is not reachable"; exit 1; }
+          curl -I http://147.93.105.228:3000 || { echo "Validation failed: Service is not reachable"; exit 1; }
           echo "Validation successful: Service is up and running."
